# Generated by Django 4.2.9 on 2024-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
