# Generated by Django 4.2.9 on 2024-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='image2',
            field=models.TextField(default=15),
            preserve_default=False,
        ),
    ]
