# Generated by Django 4.2.9 on 2024-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_items', '0002_mosaic_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='image3',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaic',
            name='image4',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaic',
            name='image5',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
