# Generated by Django 4.2.9 on 2024-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_items', '0003_mosaic_image3_mosaic_image4_mosaic_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='categoru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
